import { db } from "./db";
import { workspaces, copilotRules, provisioningRequests } from "@shared/schema";

async function seed() {
  console.log("Seeding database...");

  await db.delete(copilotRules);
  await db.delete(provisioningRequests);
  await db.delete(workspaces);

  const ws = await db.insert(workspaces).values([
    {
      displayName: "DEAL-Project Phoenix",
      type: "TEAM",
      projectType: "DEAL",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 3,
      primarySteward: "Michael Chen",
      secondarySteward: "Lisa Park",
      size: "450 MB",
      usage: "High",
      lastActive: "2 days ago",
      externalSharing: false,
      department: "M&A",
      costCenter: "CC-4100",
      projectCode: "PHX-001",
    },
    {
      displayName: "HR Leadership",
      type: "SHAREPOINT_SITE",
      projectType: "GENERAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 1,
      primarySteward: "Sarah Jenkins",
      secondarySteward: null,
      size: "1.2 GB",
      usage: "Medium",
      lastActive: "5 hours ago",
      externalSharing: false,
      department: "Human Resources",
      costCenter: "",
      projectCode: "PRJ-992",
    },
    {
      displayName: "Marketing Q3 Campaign",
      type: "TEAM",
      projectType: "GENERAL",
      sensitivity: "INTERNAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 4,
      primarySteward: "David Kim",
      secondarySteward: "Rachel Moore",
      size: "2.8 GB",
      usage: "Very High",
      lastActive: "Just now",
      externalSharing: true,
      department: "Marketing",
      costCenter: "CC-2200",
      projectCode: "MKT-Q3",
    },
    {
      displayName: "All Company Updates",
      type: "M365_GROUP",
      projectType: "GENERAL",
      sensitivity: "PUBLIC",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 2,
      primarySteward: "Emily Watson",
      secondarySteward: "James Liu",
      size: "8.5 GB",
      usage: "High",
      lastActive: "1 day ago",
      externalSharing: true,
      department: "Corporate Communications",
      costCenter: "CC-1000",
      projectCode: "",
    },
    {
      displayName: "DEAL-Mergers & Acquisitions",
      type: "TEAM",
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 2,
      primarySteward: "Robert Taylor",
      secondarySteward: "Amanda Foster",
      size: "310 MB",
      usage: "Low",
      lastActive: "1 week ago",
      externalSharing: false,
      department: "M&A",
      costCenter: "",
      projectCode: "MA-2024",
    },
    {
      displayName: "Q4 Finance Reporting",
      type: "POWER_BI",
      projectType: "GENERAL",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 2,
      primarySteward: "Kevin Zhang",
      secondarySteward: "Maria Santos",
      size: "15 MB",
      usage: "Medium",
      lastActive: "10 mins ago",
      externalSharing: false,
      department: "Finance",
      costCenter: "CC-3000",
      projectCode: "FIN-Q4",
    },
    {
      displayName: "Engineering Specs Sync",
      type: "LOOP_WORKSPACE",
      projectType: "GENERAL",
      sensitivity: "INTERNAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 5,
      primarySteward: "Tom Anderson",
      secondarySteward: "Priya Sharma",
      size: "45 MB",
      usage: "High",
      lastActive: "1 hour ago",
      externalSharing: true,
      department: "Engineering",
      costCenter: "CC-5000",
      projectCode: "ENG-SYNC",
    },
    {
      displayName: "R&D Competitor Research",
      type: "COPILOT_NOTEBOOK",
      projectType: "GENERAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 1,
      primarySteward: "Diana Ross",
      secondarySteward: null,
      size: "5 MB",
      usage: "Medium",
      lastActive: "2 days ago",
      externalSharing: false,
      department: "R&D",
      costCenter: "",
      projectCode: "",
    },
    {
      displayName: "PORTCO-Acme Corp Integration",
      type: "TEAM",
      projectType: "PORTCO",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 3,
      primarySteward: "Chris Johnson",
      secondarySteward: "Nina Patel",
      size: "720 MB",
      usage: "High",
      lastActive: "3 hours ago",
      externalSharing: false,
      department: "Operations",
      costCenter: "CC-6100",
      projectCode: "ACME-INT",
    },
    {
      displayName: "PORTCO-BrightStar Holdings",
      type: "SHAREPOINT_SITE",
      projectType: "PORTCO",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "COMPLETE",
      copilotReady: false,
      owners: 2,
      primarySteward: "Alex Rivera",
      secondarySteward: "Jordan Blake",
      size: "3.1 GB",
      usage: "Very High",
      lastActive: "30 mins ago",
      externalSharing: false,
      department: "Portfolio Management",
      costCenter: "CC-7000",
      projectCode: "BSH-2024",
    },
    {
      displayName: "Legal Contract Review",
      type: "SHAREPOINT_SITE",
      projectType: "GENERAL",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 2,
      primarySteward: "Patricia Wong",
      secondarySteward: "Steven Grant",
      size: "890 MB",
      usage: "Medium",
      lastActive: "4 hours ago",
      externalSharing: false,
      department: "Legal",
      costCenter: "CC-8000",
      projectCode: "LEG-CR",
    },
    {
      displayName: "DEAL-Titan Acquisition",
      type: "TEAM",
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 2,
      primarySteward: "Mark Sullivan",
      secondarySteward: "Jennifer Lee",
      size: "156 MB",
      usage: "Low",
      lastActive: "3 days ago",
      externalSharing: false,
      department: "M&A",
      costCenter: "",
      projectCode: "TITAN-ACQ",
    },
  ]).returning();

  for (const w of ws) {
    const rules = [];
    rules.push({
      workspaceId: w.id,
      ruleName: "Sensitivity Labeled",
      ruleResult: w.sensitivity ? "PASS" : "FAIL",
      ruleDescription: "Workspace must have a Purview sensitivity label applied.",
    });
    rules.push({
      workspaceId: w.id,
      ruleName: "Metadata Complete",
      ruleResult: w.metadataStatus === "COMPLETE" ? "PASS" : "FAIL",
      ruleDescription: "All required governance metadata fields must be populated.",
    });
    rules.push({
      workspaceId: w.id,
      ruleName: "Sharing Policy",
      ruleResult: w.sensitivity === "HIGHLY_CONFIDENTIAL" && w.externalSharing ? "FAIL" : "PASS",
      ruleDescription: "External sharing policy must align with sensitivity classification.",
    });
    rules.push({
      workspaceId: w.id,
      ruleName: "Dual Ownership",
      ruleResult: w.owners >= 2 ? "PASS" : "FAIL",
      ruleDescription: "Workspace must have at least two active owners to prevent orphaned data.",
    });

    await db.insert(copilotRules).values(rules);
  }

  await db.insert(provisioningRequests).values([
    {
      workspaceName: "Project Helios",
      workspaceType: "TEAM",
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      externalSharing: false,
      primarySteward: "Mark Sullivan",
      secondarySteward: "Jennifer Lee",
      status: "PENDING",
      requestedBy: "mark.sullivan@platinumequity.com",
      governedName: "DEAL-PROJECT-HELIOS",
    },
    {
      workspaceName: "Zenith Corp Onboarding",
      workspaceType: "SHAREPOINT_SITE",
      projectType: "PORTCO",
      sensitivity: "CONFIDENTIAL",
      externalSharing: false,
      primarySteward: "Nina Patel",
      secondarySteward: "Chris Johnson",
      status: "PENDING",
      requestedBy: "nina.patel@platinumequity.com",
      governedName: "PORTCO-ZENITH-CORP-ONBOARDING",
    },
    {
      workspaceName: "Annual Compliance Review",
      workspaceType: "TEAM",
      projectType: "GENERAL",
      sensitivity: "INTERNAL",
      externalSharing: true,
      primarySteward: "Patricia Wong",
      secondarySteward: "Steven Grant",
      status: "APPROVED",
      requestedBy: "patricia.wong@platinumequity.com",
      governedName: "GEN-ANNUAL-COMPLIANCE-REVIEW",
    },
    {
      workspaceName: "Due Diligence - Omega",
      workspaceType: "TEAM",
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      externalSharing: false,
      primarySteward: "Robert Taylor",
      secondarySteward: "Amanda Foster",
      status: "PROVISIONED",
      requestedBy: "robert.taylor@platinumequity.com",
      governedName: "DEAL-DUE-DILIGENCE-OMEGA",
    },
  ]);

  console.log(`Seeded ${ws.length} workspaces, copilot rules, and 4 provisioning requests.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
