import { db } from "./db";
import { workspaces, copilotRules, provisioningRequests } from "@shared/schema";

async function seed() {
  console.log("Seeding database...");

  await db.delete(copilotRules);
  await db.delete(provisioningRequests);
  await db.delete(workspaces);

  const ws = await db.insert(workspaces).values([
    {
      displayName: "DEAL-Project Phoenix",
      type: "TEAM_SITE",
      teamsConnected: true,
      projectType: "DEAL",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 3,
      siteOwners: [
        { displayName: "Michael Chen", mail: "michael.chen@synozur.com" },
        { displayName: "Lisa Park", mail: "lisa.park@synozur.com" },
        { displayName: "Sarah Jenkins", mail: "sarah.jenkins@synozur.com" },
      ],
      size: "450 MB",
      usage: "High",
      lastActive: "2 days ago",
      externalSharing: false,
      department: "M&A",
      costCenter: "CC-4100",
      projectCode: "PHX-001",
    },
    {
      displayName: "HR Leadership",
      type: "COMMUNICATION_SITE",
      teamsConnected: false,
      projectType: "GENERAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 1,
      siteOwners: [
        { displayName: "Sarah Jenkins", mail: "sarah.jenkins@synozur.com" },
      ],
      size: "1.2 GB",
      usage: "Medium",
      lastActive: "5 hours ago",
      externalSharing: false,
      department: "Human Resources",
      costCenter: "",
      projectCode: "PRJ-992",
    },
    {
      displayName: "Marketing Q3 Campaign",
      type: "TEAM_SITE",
      teamsConnected: true,
      projectType: "GENERAL",
      sensitivity: "INTERNAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 4,
      siteOwners: [
        { displayName: "David Kim", mail: "david.kim@synozur.com" },
        { displayName: "Rachel Moore", mail: "rachel.moore@synozur.com" },
        { displayName: "Tom Anderson", mail: "tom.anderson@synozur.com" },
        { displayName: "Priya Sharma", mail: "priya.sharma@synozur.com" },
      ],
      size: "2.8 GB",
      usage: "Very High",
      lastActive: "Just now",
      externalSharing: true,
      department: "Marketing",
      costCenter: "CC-2200",
      projectCode: "MKT-Q3",
    },
    {
      displayName: "All Company Updates",
      type: "COMMUNICATION_SITE",
      teamsConnected: false,
      projectType: "GENERAL",
      sensitivity: "PUBLIC",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 2,
      siteOwners: [
        { displayName: "Emily Watson", mail: "emily.watson@synozur.com" },
        { displayName: "James Liu", mail: "james.liu@synozur.com" },
      ],
      size: "8.5 GB",
      usage: "High",
      lastActive: "1 day ago",
      externalSharing: true,
      department: "Corporate Communications",
      costCenter: "CC-1000",
      projectCode: "",
    },
    {
      displayName: "DEAL-Mergers & Acquisitions",
      type: "TEAM_SITE",
      teamsConnected: true,
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 2,
      siteOwners: [
        { displayName: "Robert Taylor", mail: "robert.taylor@synozur.com" },
        { displayName: "Amanda Foster", mail: "amanda.foster@synozur.com" },
      ],
      size: "310 MB",
      usage: "Low",
      lastActive: "1 week ago",
      externalSharing: false,
      department: "M&A",
      costCenter: "",
      projectCode: "MA-2024",
    },
    {
      displayName: "Q4 Finance Reporting",
      type: "TEAM_SITE",
      teamsConnected: false,
      projectType: "GENERAL",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 2,
      siteOwners: [
        { displayName: "Kevin Zhang", mail: "kevin.zhang@synozur.com" },
        { displayName: "Maria Santos", mail: "maria.santos@synozur.com" },
      ],
      size: "15 MB",
      usage: "Medium",
      lastActive: "10 mins ago",
      externalSharing: false,
      department: "Finance",
      costCenter: "CC-3000",
      projectCode: "FIN-Q4",
    },
    {
      displayName: "Engineering Specs Sync",
      type: "TEAM_SITE",
      teamsConnected: true,
      projectType: "GENERAL",
      sensitivity: "INTERNAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 5,
      siteOwners: [
        { displayName: "Tom Anderson", mail: "tom.anderson@synozur.com" },
        { displayName: "Priya Sharma", mail: "priya.sharma@synozur.com" },
        { displayName: "David Kim", mail: "david.kim@synozur.com" },
        { displayName: "Rachel Moore", mail: "rachel.moore@synozur.com" },
        { displayName: "James Liu", mail: "james.liu@synozur.com" },
      ],
      size: "45 MB",
      usage: "High",
      lastActive: "1 hour ago",
      externalSharing: true,
      department: "Engineering",
      costCenter: "CC-5000",
      projectCode: "ENG-SYNC",
    },
    {
      displayName: "R&D Competitor Research",
      type: "COMMUNICATION_SITE",
      teamsConnected: false,
      projectType: "GENERAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 1,
      siteOwners: [
        { displayName: "Diana Ross", mail: "diana.ross@synozur.com" },
      ],
      size: "5 MB",
      usage: "Medium",
      lastActive: "2 days ago",
      externalSharing: false,
      department: "R&D",
      costCenter: "",
      projectCode: "",
    },
    {
      displayName: "PORTCO-Acme Corp Integration",
      type: "TEAM_SITE",
      teamsConnected: true,
      projectType: "PORTCO",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Default 7 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 3,
      siteOwners: [
        { displayName: "Chris Johnson", mail: "chris.johnson@synozur.com" },
        { displayName: "Nina Patel", mail: "nina.patel@synozur.com" },
        { displayName: "Alex Rivera", mail: "alex.rivera@synozur.com" },
      ],
      size: "720 MB",
      usage: "High",
      lastActive: "3 hours ago",
      externalSharing: false,
      department: "Operations",
      costCenter: "CC-6100",
      projectCode: "ACME-INT",
    },
    {
      displayName: "PORTCO-BrightStar Holdings",
      type: "COMMUNICATION_SITE",
      teamsConnected: false,
      projectType: "PORTCO",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "COMPLETE",
      copilotReady: false,
      owners: 2,
      siteOwners: [
        { displayName: "Alex Rivera", mail: "alex.rivera@synozur.com" },
        { displayName: "Jordan Blake", mail: "jordan.blake@synozur.com" },
      ],
      size: "3.1 GB",
      usage: "Very High",
      lastActive: "30 mins ago",
      externalSharing: false,
      department: "Portfolio Management",
      costCenter: "CC-7000",
      projectCode: "BSH-2024",
    },
    {
      displayName: "Legal Contract Review",
      type: "HUB_SITE",
      teamsConnected: false,
      projectType: "GENERAL",
      sensitivity: "CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "COMPLETE",
      copilotReady: true,
      owners: 2,
      siteOwners: [
        { displayName: "Patricia Wong", mail: "patricia.wong@synozur.com" },
        { displayName: "Steven Grant", mail: "steven.grant@synozur.com" },
      ],
      size: "890 MB",
      usage: "Medium",
      lastActive: "4 hours ago",
      externalSharing: false,
      department: "Legal",
      costCenter: "CC-8000",
      projectCode: "LEG-CR",
    },
    {
      displayName: "DEAL-Titan Acquisition",
      type: "TEAM_SITE",
      teamsConnected: true,
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      retentionPolicy: "Executive 10 Year",
      metadataStatus: "MISSING_REQUIRED",
      copilotReady: false,
      owners: 2,
      siteOwners: [
        { displayName: "Mark Sullivan", mail: "mark.sullivan@synozur.com" },
        { displayName: "Jennifer Lee", mail: "jennifer.lee@synozur.com" },
      ],
      size: "156 MB",
      usage: "Low",
      lastActive: "3 days ago",
      externalSharing: false,
      department: "M&A",
      costCenter: "",
      projectCode: "TITAN-ACQ",
    },
  ]).returning();

  for (const w of ws) {
    const rules = [];
    rules.push({
      workspaceId: w.id,
      ruleName: "Sensitivity Labeled",
      ruleResult: w.sensitivity ? "PASS" : "FAIL",
      ruleDescription: "Workspace must have a Purview sensitivity label applied.",
    });
    rules.push({
      workspaceId: w.id,
      ruleName: "Metadata Complete",
      ruleResult: w.metadataStatus === "COMPLETE" ? "PASS" : "FAIL",
      ruleDescription: "All required governance metadata fields must be populated.",
    });
    rules.push({
      workspaceId: w.id,
      ruleName: "Sharing Policy",
      ruleResult: w.sensitivity === "HIGHLY_CONFIDENTIAL" && w.externalSharing ? "FAIL" : "PASS",
      ruleDescription: "External sharing policy must align with sensitivity classification.",
    });
    rules.push({
      workspaceId: w.id,
      ruleName: "Dual Ownership",
      ruleResult: w.owners >= 2 ? "PASS" : "FAIL",
      ruleDescription: "Workspace must have at least two active owners to prevent orphaned data.",
    });

    await db.insert(copilotRules).values(rules);
  }

  await db.insert(provisioningRequests).values([
    {
      workspaceName: "Project Helios",
      workspaceType: "TEAM_SITE",
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      externalSharing: false,
      siteOwners: [
        { displayName: "Mark Sullivan", mail: "mark.sullivan@synozur.com" },
        { displayName: "Jennifer Lee", mail: "jennifer.lee@synozur.com" },
      ],
      status: "PENDING",
      requestedBy: "mark.sullivan@synozur.com",
      governedName: "DEAL-PROJECT-HELIOS",
    },
    {
      workspaceName: "Zenith Corp Onboarding",
      workspaceType: "COMMUNICATION_SITE",
      projectType: "PORTCO",
      sensitivity: "CONFIDENTIAL",
      externalSharing: false,
      siteOwners: [
        { displayName: "Nina Patel", mail: "nina.patel@synozur.com" },
        { displayName: "Chris Johnson", mail: "chris.johnson@synozur.com" },
      ],
      status: "PENDING",
      requestedBy: "nina.patel@synozur.com",
      governedName: "PORTCO-ZENITH-CORP-ONBOARDING",
    },
    {
      workspaceName: "Annual Compliance Review",
      workspaceType: "TEAM_SITE",
      projectType: "GENERAL",
      sensitivity: "INTERNAL",
      externalSharing: true,
      siteOwners: [
        { displayName: "Patricia Wong", mail: "patricia.wong@synozur.com" },
        { displayName: "Steven Grant", mail: "steven.grant@synozur.com" },
      ],
      status: "APPROVED",
      requestedBy: "patricia.wong@synozur.com",
      governedName: "GEN-ANNUAL-COMPLIANCE-REVIEW",
    },
    {
      workspaceName: "Due Diligence - Omega",
      workspaceType: "TEAM_SITE",
      projectType: "DEAL",
      sensitivity: "HIGHLY_CONFIDENTIAL",
      externalSharing: false,
      siteOwners: [
        { displayName: "Robert Taylor", mail: "robert.taylor@synozur.com" },
        { displayName: "Amanda Foster", mail: "amanda.foster@synozur.com" },
      ],
      status: "PROVISIONED",
      requestedBy: "robert.taylor@synozur.com",
      governedName: "DEAL-DUE-DILIGENCE-OMEGA",
    },
  ]);

  console.log(`Seeded ${ws.length} workspaces, copilot rules, and 4 provisioning requests.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
